"""Golden tests for the generated Cilium local-redirect policy.

Two layers, both mandatory:

1. **Golden fixture** — the generated manifest must equal
   ``fixtures/golden-lrp-manifest.json`` byte-for-byte. Any change to the
   generated policy is a reviewable diff, not a silent drift.
2. **Vendored CRD validation** — the same manifest is validated with
   jsonschema against the ``CiliumLocalRedirectPolicy`` CRD vendored from
   cilium **v1.17.3** (``fixtures/cilium-lrp-crd.yaml``). This is the
   build-time verification of the candidate CRD primitive named in the
   spec: if a future Cilium version changes the schema, this test fails
   and the vendored CRD is the thing to update deliberately.

The manifest this test pins is generated by the module under test — the
fixture was committed after eyeballing it, never hand-written.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from types import SimpleNamespace

import pytest
import yaml
from jsonschema import Draft202012Validator

from core.integrations.honey_router.route import (
    CILIUM_LRP_CRD_NAME,
    LRP_API_VERSION,
    LRP_KIND,
    DecoyTarget,
    attacker_label_value,
    build_local_redirect_policy,
    policy_name_for,
)

FIXTURES = Path(__file__).parent / "fixtures"

DECOY = DecoyTarget(
    decoy_id="decoy-ssh-01",
    name="SSH decoy (voltage-grid edge)",
    kind="ssh",
    endpoint_host="10.42.0.77",
    endpoint_port=2222,
    namespace="vigil-decoys",
)
ATTACKER = "203.0.113.7"


def _crd_schema() -> dict:
    crd = yaml.safe_load((FIXTURES / "cilium-lrp-crd.yaml").read_text())
    assert crd["metadata"]["name"] == CILIUM_LRP_CRD_NAME
    version = next(v for v in crd["spec"]["versions"] if v["name"] == "v2")
    return version["schema"]["openAPIV3Schema"]


class TestGoldenManifest:
    def test_manifest_matches_committed_golden_fixture(self):
        golden = json.loads((FIXTURES / "golden-lrp-manifest.json").read_text())
        generated = build_local_redirect_policy(ATTACKER, DECOY)
        assert generated == golden

    def test_manifest_validates_against_vendored_cilium_v1_17_3_crd(self):
        manifest = build_local_redirect_policy(ATTACKER, DECOY)
        errors = sorted(
            Draft202012Validator(_crd_schema()).iter_errors(manifest),
            key=lambda e: list(e.path),
        )
        assert not errors, [e.message for e in errors]

    def test_explicit_namespace_overrides_decoy_namespace(self):
        manifest = build_local_redirect_policy(ATTACKER, DECOY, namespace="vigil")
        assert manifest["metadata"]["namespace"] == "vigil"


class TestPolicyNaming:
    def test_name_is_deterministic_and_rfc1123_safe(self):
        for ip in [ATTACKER, "10.0.0.1", "2001:db8::dead:beef", "weird input!!"]:
            name = policy_name_for(ip)
            assert name == policy_name_for(ip), "must be stable"
            assert re.fullmatch(r"[a-z0-9]([-a-z0-9]*[a-z0-9])?", name), name
            assert len(name) <= 63, name

    def test_name_never_embeds_the_raw_attacker_ip(self):
        name = policy_name_for(ATTACKER)
        assert "203" not in name and "113" not in name and "7" != name[-1]

    def test_attacker_label_value_sanitizes_control_chars(self):
        value = attacker_label_value("bad label/with:chars!")
        assert re.fullmatch(r"ip-[a-zA-Z0-9.\-]*", value), value


class TestGeneratorValidation:
    def test_hostname_endpoint_is_a_loud_value_error(self):
        decoy = SimpleNamespace(
            decoy_id="d1",
            name="n",
            kind="ssh",
            endpoint_host="decoy.vigil.svc",
            endpoint_port=2222,
            namespace="ns",
        )
        with pytest.raises(ValueError, match="routable IP|decoy.vigil.svc|ip"):
            build_local_redirect_policy(ATTACKER, decoy)  # type: ignore[arg-type]

    def test_canonical_constants_are_pinned(self):
        # The CRD name is what the backend probes for CNI detection and what
        # the runbook kubectl-waits on — renaming it silently breaks both.
        assert LRP_KIND == "CiliumLocalRedirectPolicy"
        assert LRP_API_VERSION == "cilium.io/v2"
        assert CILIUM_LRP_CRD_NAME == "ciliumlocalredirectpolicies.cilium.io"
