#!/usr/bin/env bash
# End-to-end proof of the compose edge profile: the full loop over real
# containers —
#
#     observation → reversible block → TTL revert → journaled → imported
#     → visible in the findings and approval surfaces
#
# Flow (scripts/edge_compose_seed.py does the signing steps):
#   1. mint the DSSE signing keypair + trust root
#   2. bring up the central stack (postgres/redis/bifrost/backend)
#   3. seed: publish a tier-2 bundle, mint an enrollment token
#   4. start the `edge` daemon (gateway mode, bridge netns — the host
#      firewall is never touched; containment lands in a dedicated
#      `vigil_edge` nftables table)
#   5. write one Suricata EVE observation (egress to a bundle IOC)
#   6. watch nftables: the block appears, the TTL reaper removes it
#   7. watch Postgres: the journal imported as findings + an executed,
#      edge-provenanced approval row
#
# Requires: docker compose; python3 with the repo's requirements.lock
# installed (for the keypair step). Evidence lands in
# infra/docker/edge-e2e/e2e-evidence.txt; teardown keeps volumes so the
# run is repeatable (the seed versions bundles monotonically).
#
# The one thing this proves nothing about is a real kernel firewall on a
# real gateway under a real WAN cut — that is the staging drill,
# docs/edge-staging-drill.md.
set -Eeuo pipefail

REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT/infra/docker"

NODE_ID=${VIGIL_EDGE_NODE_ID:-gw-compose-e2e-$(date +%s)}
E2E_SECRET=${VIGIL_EDGE_ENROLLMENT_SECRET:-local-dev-edge-enrollment-secret}
SCOPE='{"vpc": "vpc-compose-e2e", "cidrs": ["10.42.0.0/16"], "node_selector": {"vigil.ai/edge-role": "gateway"}}'
BLOCKED_IP="203.0.113.55"
WORK="$PWD/edge-e2e"
EVIDENCE="$WORK/e2e-evidence.txt"
COMPOSE_CENTRAL=(docker compose -f docker-compose.yml -f "$WORK/compose.e2e.yml")
COMPOSE_EDGE=(docker compose -f docker-compose.yml --profile edge --env-file "$WORK/edge.env")

mkdir -p "$WORK"

cleanup() {
  # Keep volumes (repeatable runs); remove containers and the edge profile.
  "${COMPOSE_EDGE[@]}" down --remove-orphans >/dev/null 2>&1 || true
}
trap cleanup EXIT

fail() {
  echo "FAIL: $*" | tee -a "$EVIDENCE"
  docker compose -f docker-compose.yml --profile edge logs --tail=40 edge >>"$EVIDENCE" 2>&1 || true
  exit 1
}

# wait_for <description> <timeout_s> <command...> — poll until success.
wait_for() {
  local desc=$1 timeout=$2
  shift 2
  local deadline=$((SECONDS + timeout))
  until "$@" >/dev/null 2>&1; do
    if ((SECONDS >= deadline)); then
      fail "$desc (timed out after ${timeout}s)"
    fi
    sleep 2
  done
  echo "ok: $desc" | tee -a "$EVIDENCE"
}

psql_edge() {
  docker compose exec -T postgres psql -U deeptempo -d deeptempo_soc -tAc "$1"
}

# The block is gone when the vigil_edge table no longer mentions the IOC.
block_gone() {
  ! "${COMPOSE_EDGE[@]}" exec -T edge nft list table inet vigil_edge 2>/dev/null \
    | grep -q "$BLOCKED_IP"
}

# The journal imported when at least one finding carries the node's source.
finding_imported() {
  [ "$(psql_edge "SELECT count(*) FROM findings WHERE data_source = 'edge:$NODE_ID'")" -ge 1 ]
}

{
  echo "edge compose e2e — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "node: $NODE_ID"
  echo "scope: $SCOPE"
} >"$EVIDENCE"

# ── 1. Signing keypair + trust root ────────────────────────────────────────
echo "== generating DSSE signing keypair"
PYTHONPATH="$REPO_ROOT" python3 - <<PY
import base64, json
from datetime import timedelta
from core.edge import signing

private_pem, public_b64, _ = signing.generate_signing_keypair()
open("$WORK/signing-key.pem", "w").write(private_pem)
trust_root = signing.build_trust_root(
    public_b64,
    version=1,
    issued_at=signing.utcnow(),
    expires_at=signing.utcnow() + signing.MAX_BUNDLE_VALIDITY,
)
with open("$WORK/trust-root.dsse.json", "w") as handle:
    json.dump(trust_root, handle, indent=2, sort_keys=True)
    handle.write("\n")
print("keypair written")
PY

# The backend verifies stored bundles before serving them, so it needs the
# same key. In production this mount lives in an operator override file —
# exactly what we generate here.
cat >"$WORK/compose.e2e.yml" <<'YML'
# Generated by scripts/edge_compose_e2e.sh: mounts the dev signing key for
# the backend's edge control plane. Production deployments do the same via
# their own override (docs/edge-operator-guide.md).
services:
  backend:
    volumes:
      - ./edge-e2e/signing-key.pem:/run/secrets/edge_bundle_signing_key:ro
    environment:
      VIGIL_EDGE_SIGNING_KEY_FILE: /run/secrets/edge_bundle_signing_key
YML

# ── 2. Central stack up ────────────────────────────────────────────────────
echo "== starting the central stack"
VIGIL_EDGE_ENROLLMENT_SECRET="$E2E_SECRET" "${COMPOSE_CENTRAL[@]}" up -d --build backend
wait_for "backend /api/health" 300 "${COMPOSE_CENTRAL[@]}" exec -T backend \
  python -c "import urllib.request; assert urllib.request.urlopen('http://localhost:6987/api/health').status == 200"

# ── 3. Seed: bundle + enrollment token ─────────────────────────────────────
echo "== seeding bundle + enrollment token"
"${COMPOSE_CENTRAL[@]}" run --rm --no-deps \
  -v "$REPO_ROOT/scripts:/seed:ro" \
  -v "$WORK:/edge-e2e" \
  -e VIGIL_EDGE_ENROLLMENT_SECRET="$E2E_SECRET" \
  -e VIGIL_EDGE_SEGMENT_SCOPE="$SCOPE" \
  -e VIGIL_EDGE_SIGNING_KEY_FILE=/edge-e2e/signing-key.pem \
  backend python /seed/edge_compose_seed.py \
  --node-id "$NODE_ID" --out /edge-e2e | tee -a "$EVIDENCE"

# Host path of the trust root for the edge service's bind mount.
echo "VIGIL_EDGE_TRUST_STORE=$WORK/trust-root.dsse.json" >>"$WORK/edge.env"
echo "VIGIL_EDGE_MODEL=" >>"$WORK/edge.env" # deterministic-only: no Ollama here
echo "VIGIL_EDGE_SYNC_INTERVAL_SECONDS=2" >>"$WORK/edge.env"
echo "VIGIL_EDGE_REAPER_INTERVAL_SECONDS=2" >>"$WORK/edge.env"

# ── 4. Edge daemon up, wait for SYNCED ─────────────────────────────────────
echo "== starting the edge daemon"
"${COMPOSE_EDGE[@]}" up -d --build edge
wait_for "edge daemon SYNCED (enrolled + bundle verified)" 180 \
  curl -sf http://127.0.0.1:9091/health
curl -sf http://127.0.0.1:9091/health | grep -q '"state": "synced"' \
  || fail "edge daemon health is not synced"
curl -sf http://127.0.0.1:9091/health | tee -a "$EVIDENCE"

# ── 5. Observation ─────────────────────────────────────────────────────────
echo "== writing the EVE observation (egress to $BLOCKED_IP)"
EVE_LINE=$(printf '{"event_type":"flow","timestamp":"%s","src_ip":"10.42.7.7","dest_ip":"%s","proto":"tcp"}' \
  "$(date -u +%Y-%m-%dT%H:%M:%S.000000Z)" "$BLOCKED_IP")
echo "$EVE_LINE" | tee -a "$EVIDENCE"
"${COMPOSE_EDGE[@]}" exec -T edge sh -c "echo '$EVE_LINE' >> /data/eve.json"

# ── 6. Reversible block, then the TTL revert ───────────────────────────────
wait_for "nftables vigil_edge table blocks $BLOCKED_IP" 60 \
  "${COMPOSE_EDGE[@]}" exec -T edge nft list table inet vigil_edge
"${COMPOSE_EDGE[@]}" exec -T edge nft list table inet vigil_edge | tee -a "$EVIDENCE" | grep -q "$BLOCKED_IP" \
  || fail "block rule for $BLOCKED_IP not found in the vigil_edge table"

wait_for "TTL reaper reverted the block" 60 block_gone

# ── 7. Imported: findings + approval surface ───────────────────────────────
wait_for "journal imported (findings row)" 90 finding_imported

{
  echo "== findings imported:"
  psql_edge "SELECT finding_id, title, severity, data_source, external_id FROM findings WHERE data_source = 'edge:$NODE_ID' ORDER BY created_at" || true
  echo "== approval rows (edge provenance):"
  psql_edge "SELECT action_id, action_type, target, status, created_by FROM approval_actions WHERE created_by = 'edge:$NODE_ID' ORDER BY created_at" || true
} >>"$EVIDENCE"

APPROVAL_ROWS=$(psql_edge "SELECT count(*) FROM approval_actions WHERE created_by = 'edge:$NODE_ID' AND action_type = 'block_ip' AND status = 'executed'")
[ "$APPROVAL_ROWS" -ge 1 ] || fail "no executed block_ip approval row for edge:$NODE_ID"
echo "ok: executed edge-provenanced approval row present" | tee -a "$EVIDENCE"

{
  echo "== edge daemon log tail:"
  docker compose -f docker-compose.yml --profile edge logs --tail=25 edge || true
} >>"$EVIDENCE"

echo "EDGE COMPOSE E2E: PASS — evidence in $EVIDENCE"
