import { IntegrationMetadata } from './integrationSchema'
import { basePath } from './basePath'

export const INTEGRATIONS: IntegrationMetadata[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'Reference / Platform',
    description: 'Access GitHub repositories, issues, pull requests, and code search via the official MCP server.',
    functionality_type: 'Source Control & Collaboration',
    fields: [
      {
        name: 'token',
        label: 'Personal Access Token',
        type: 'password',
        required: true,
        placeholder: 'ghp_...',
        helpText: 'Generate at GitHub → Settings → Developer settings → Personal access tokens → Tokens (classic). Recommended scopes: repo, workflow, read:org, read:user, user:email.',
      },
    ],
    docs_url: 'https://docs.github.com/en/rest',
  },

  {
    id: 'virustotal',
    name: 'VirusTotal',
    category: 'Threat Intelligence',
    description: 'Check file hashes, URLs, domains, and IPs against VirusTotal\'s threat intelligence database.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your VirusTotal API key',
        helpText: 'Get your API key from https://www.virustotal.com/gui/my-apikey',
      },
    ],
    docs_url: 'https://developers.virustotal.com/reference/overview',
  },
  {
    id: 'alienvault-otx',
    name: 'AlienVault OTX',
    category: 'Threat Intelligence',
    description: 'Access threat intelligence from AlienVault Open Threat Exchange.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your AlienVault OTX API key',
        helpText: 'Get your API key from https://otx.alienvault.com/api',
      },
    ],
    docs_url: 'https://otx.alienvault.com/api',
  },
  {
    id: 'shodan',
    name: 'Shodan',
    category: 'Threat Intelligence',
    description: 'Search for internet-connected devices and gather intelligence on IP addresses.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your Shodan API key',
        helpText: 'Get your API key from https://account.shodan.io/',
      },
    ],
    docs_url: 'https://developer.shodan.io/',
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'Threat Intelligence',
    description: 'Search and read web pages during an investigation — vendor advisories, CVE writeups, and reporting on an observable.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'fc-...',
        helpText: 'Get your API key from https://www.firecrawl.dev/app/api-keys',
      },
    ],
    docs_url: 'https://docs.firecrawl.dev/',
  },
  {
    id: 'misp',
    name: 'MISP',
    category: 'Threat Intelligence',
    description: 'Connect to MISP (Malware Information Sharing Platform) for threat sharing.',
    functionality_type: 'Data Enrichment',
    proxy_supported: true,
    fields: [
      {
        name: 'url',
        label: 'MISP Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://misp.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        placeholder: 'Your MISP API key',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
    ],
    docs_url: 'https://www.misp-project.org/documentation/',
  },
  {
    id: 'gcp-threat-intel',
    name: 'Google Threat Intelligence',
    category: 'Threat Intelligence',
    description: 'Google Threat Intelligence (powered by VirusTotal/Mandiant) for file, URL, domain, and IP reputation lookups, threat actor profiles, and campaign tracking.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_key',
        label: 'VirusTotal API Key',
        type: 'password',
        required: true,
        placeholder: 'Your VirusTotal API key',
        helpText: 'Uses your VirusTotal API key for Google Threat Intelligence queries. Get one at virustotal.com.',
      },
    ],
    docs_url: 'https://cloud.google.com/threat-intelligence/docs',
  },
  {
    id: 'url-analysis',
    name: 'URL Analysis',
    category: 'Threat Intelligence',
    description: 'Analyze suspicious URLs for phishing, malware, and other threats.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'service',
        label: 'Analysis Service',
        type: 'select',
        required: true,
        default: 'urlscan',
        options: [
          { value: 'urlscan', label: 'URLScan.io' },
          { value: 'google_safe_browsing', label: 'Google Safe Browsing' },
        ],
      },
    ],
    docs_url: 'https://urlscan.io/docs/api/',
  },
  {
    id: 'ip-geolocation',
    name: 'IP Geolocation',
    category: 'Threat Intelligence',
    description: 'Get geolocation data for IP addresses.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'service',
        label: 'Geolocation Service',
        type: 'select',
        required: true,
        default: 'ipapi',
        options: [
          { value: 'ipapi', label: 'IP-API.com (Free)' },
          { value: 'maxmind', label: 'MaxMind GeoIP2' },
        ],
      },
    ],
    docs_url: 'https://ip-api.com/docs',
  },

  {
    id: 'crowdstrike',
    name: 'CrowdStrike Falcon',
    category: 'EDR/XDR',
    description: 'Connect to CrowdStrike Falcon for endpoint detection and response with threat intelligence.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'Your CrowdStrike client ID',
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
        placeholder: 'Your CrowdStrike client secret',
      },
      {
        name: 'base_url',
        label: 'Base URL',
        type: 'url',
        required: true,
        default: 'https://api.crowdstrike.com',
        helpText: 'Usually https://api.crowdstrike.com or region-specific endpoint',
      },
    ],
    docs_url: 'https://www.crowdstrike.com/blog/tech-center/get-access-falcon-apis/',
  },
  {
    id: 'sentinelone',
    name: 'SentinelOne',
    category: 'EDR/XDR',
    description: 'Integrate with SentinelOne for autonomous endpoint protection with AI-powered threat detection.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'api_url',
        label: 'API URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-instance.sentinelone.net',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        placeholder: 'Your SentinelOne API token',
      },
    ],
    docs_url: 'https://usea1-partners.sentinelone.net/docs/en/using-api-tokens.html',
  },
  {
    id: 'carbon-black',
    name: 'VMware Carbon Black',
    category: 'EDR/XDR',
    description: 'Connect to VMware Carbon Black Cloud for endpoint security and threat hunting.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'url',
        label: 'Carbon Black URL',
        type: 'url',
        required: true,
        placeholder: 'https://defense.conferdeploy.net',
      },
      {
        name: 'api_id',
        label: 'API ID',
        type: 'text',
        required: true,
      },
      {
        name: 'api_key',
        label: 'API Secret Key',
        type: 'password',
        required: true,
      },
      {
        name: 'org_key',
        label: 'Organization Key',
        type: 'text',
        required: true,
      },
    ],
    docs_url: 'https://developer.carbonblack.com/',
  },
  {
    id: 'microsoft-defender',
    name: 'Microsoft Defender for Endpoint',
    category: 'EDR/XDR',
    description: 'Integrate with Microsoft Defender for Endpoint (MDE) for enterprise endpoint protection.',
    functionality_type: 'Detection & Response',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
        placeholder: 'Your Azure AD tenant ID',
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
        placeholder: 'Application (client) ID',
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/api-hello-world',
  },
  {
    id: 'loglm',
    name: 'LogLM',
    category: 'Detection & AI',
    description:
      'DeepTempo LogLM anomaly detections stream into Vigil as findings, and the LogLM model-admin panel mounts natively inside the console. Requires the paid, opt-in LogLM connector.',
    functionality_type: 'AI Detection & Model Admin',
    has_ui: true,
    fields: [
      {
        name: 'connectorUrl',
        label: 'Connector URL',
        type: 'url',
        required: true,
        placeholder: 'https://loglm-connector.internal',
        helpText:
          'Base URL of the LogLM connector — it serves the admin UI bundle, the extension manifest, and the session/model APIs. The browser calls this directly, so it must be reachable from the analyst\'s browser with CORS enabled.',
      },
      {
        name: 'mint_secret',
        label: 'Session Mint Secret',
        type: 'password',
        required: true,
        helpText:
          'Shared HMAC secret Vigil uses to request short-lived, user-scoped session tokens from the connector (matches the connector\'s CONNECTOR_BFF_SESSION_MINT_SECRET). Stored encrypted server-side; never sent to the browser.',
      },
      {
        name: 'mcp_token',
        label: 'MCP Bearer Token',
        type: 'password',
        required: true,
        helpText:
          'Static bearer token the LogLM agent tools present to the connector\'s MCP endpoint (matches the connector\'s CONNECTOR_MCP_AUTH_TOKEN). Stored encrypted server-side; never sent to the browser.',
      },
    ],
    docs_url: 'https://docs.deeptempo.ai/loglm',
  },

  {
    id: 'splunk',
    name: 'Splunk',
    category: 'SIEM',
    description: 'Connect to Splunk Enterprise or Splunk Cloud for log aggregation, search, and analysis with natural language query generation.',
    functionality_type: 'Log Analysis & SIEM',
    has_ui: true,
    proxy_supported: true,
    fields: [
      {
        name: 'server_url',
        label: 'Splunk Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://splunk.example.com:8089',
        helpText: 'Splunk management port (usually 8089)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'admin',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
        helpText: 'Leave on. For a private CA, set the CA Certificate Path instead of turning this off.',
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
      {
        name: 'lookback_hours',
        label: 'Lookback Hours',
        type: 'number',
        required: false,
        default: 168,
        placeholder: '168',
        helpText: 'Default time range for queries (in hours, default: 168 = 7 days)',
      },
    ],
    docs_url: 'https://docs.splunk.com/Documentation/Splunk/latest/RESTREF/RESTprolog',
  },
  {
    id: 'cribl-stream',
    name: 'Cribl Stream',
    category: 'Data Pipeline',
    description: 'Observability pipeline for collecting, processing, enriching, and routing security data. Normalize logs, reduce volume, and optimize data flow before AI analysis.',
    functionality_type: 'Data Pipeline & Enrichment',
    has_ui: false,
    proxy_supported: true,
    fields: [
      {
        name: 'server_url',
        label: 'Cribl Stream Server URL',
        type: 'url',
        required: true,
        placeholder: 'https://cribl.example.com:9000',
        helpText: 'Cribl Stream API endpoint (usually port 9000)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'admin',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
      },
      {
        name: 'worker_group',
        label: 'Worker Group',
        type: 'text',
        required: false,
        default: 'default',
        placeholder: 'default',
        helpText: 'Worker group to manage (default: "default")',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
        helpText: 'Leave on. Turn off only for a self-signed certificate.',
      },
    ],
    docs_url: 'https://docs.cribl.io/stream/',
  },
  {
    id: 'elastic-siem',
    name: 'Elastic Security (SIEM)',
    category: 'SIEM',
    description: 'Elastic Security SIEM with advanced analytics, threat hunting, and incident response capabilities. Also hunts over an OpenSearch-based Wazuh indexer.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'elasticsearch_url',
        label: 'Elasticsearch URL',
        type: 'url',
        required: true,
        placeholder: 'https://elasticsearch.example.com:9200',
        helpText: 'For a Wazuh indexer use https://<indexer>:9200 with basic auth for a user holding a read role on wazuh-alerts-*.',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: false,
        helpText: 'API key for authentication (recommended)',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: false,
        helpText: 'Alternative to API key',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: false,
        helpText: 'Required if using username auth',
      },
      {
        name: 'kibana_url',
        label: 'Kibana URL',
        type: 'url',
        required: false,
        placeholder: 'https://kibana.example.com:5601',
        helpText: 'Required for Elastic Security detection alert ingestion and case sync. Leave blank for a Wazuh indexer: alerts are then ingested from the index pattern directly.',
      },
      {
        name: 'index_pattern',
        label: 'Alert Index Pattern',
        type: 'text',
        required: false,
        default: '.alerts-security.alerts-default',
        helpText: 'Elasticsearch index pattern for security alerts. For a Wazuh indexer use wazuh-alerts-4.x-* and leave Kibana URL blank.',
      },
      {
        name: 'min_rule_level',
        label: 'Minimum Rule Level (Wazuh)',
        type: 'number',
        required: false,
        default: 7,
        placeholder: '7',
        helpText: 'Wazuh indexer only: ingest alerts at or above this rule level (1-16). Applies when Kibana URL is blank.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
    ],
    docs_url: 'https://www.elastic.co/guide/en/security/current/index.html',
  },
  {
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'SIEM',
    description: 'OpenSearch SIEM with the Security Analytics plugin: Sigma-rule detectors over centralized logs generate findings and alerts.',
    functionality_type: 'Log Analysis & SIEM',
    proxy_supported: true,
    fields: [
      {
        name: 'opensearch_url',
        label: 'OpenSearch URL',
        type: 'url',
        required: true,
        placeholder: 'https://opensearch.example.com:9200',
        helpText: 'The OpenSearch REST endpoint. Security Analytics findings are read from the findings indices on this cluster.',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: false,
        helpText: 'Basic auth user holding a read role on the findings indices',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: false,
        helpText: 'Required if using username auth',
      },
      {
        name: 'dashboards_url',
        label: 'OpenSearch Dashboards URL',
        type: 'url',
        required: false,
        placeholder: 'https://dashboards.example.com:5601',
        helpText: 'Optional. Used only to include the Dashboards version in the connection test.',
      },
      {
        name: 'index_pattern',
        label: 'Findings Index Pattern',
        type: 'text',
        required: false,
        default: '.opensearch-sap-*-findings-*',
        helpText: 'OpenSearch index pattern the Security Analytics findings are read from.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
    ],
    docs_url: 'https://opensearch.org/docs/latest/security-analytics/',
  },
  {
    id: 'azure-sentinel',
    name: 'Microsoft Sentinel',
    category: 'SIEM',
    description: 'Microsoft Azure Sentinel cloud-native SIEM with AI-powered threat detection and response.',
    functionality_type: 'Log Analysis & SIEM',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
      {
        name: 'subscription_id',
        label: 'Subscription ID',
        type: 'text',
        required: true,
      },
      {
        name: 'resource_group',
        label: 'Resource Group',
        type: 'text',
        required: true,
      },
      {
        name: 'workspace_name',
        label: 'Workspace Name',
        type: 'text',
        required: true,
        helpText: 'Sentinel workspace resource name. The Log Analytics workspace GUID is a different value.',
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/azure/sentinel/',
  },
  {
    id: 'gcp-secops',
    name: 'Google SecOps (Chronicle)',
    category: 'SIEM',
    description: 'Google Security Operations (formerly Chronicle) for cloud-native threat detection, investigation, and response. Query security telemetry with UDM search and detection rules.',
    functionality_type: 'Log Analysis & SIEM',
    fields: [
      {
        name: 'project_id',
        label: 'GCP Project ID',
        type: 'text',
        required: true,
        placeholder: 'my-gcp-project',
        helpText: 'The Google Cloud project ID linked to your Chronicle instance.',
      },
      {
        name: 'customer_id',
        label: 'Chronicle Customer ID',
        type: 'text',
        required: true,
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
        helpText: 'Your Chronicle customer ID (UUID format).',
      },
      {
        name: 'region',
        label: 'Region',
        type: 'text',
        required: false,
        placeholder: 'us',
        helpText: 'Chronicle region (e.g., us, europe, asia-southeast1). Defaults to us.',
      },
    ],
    docs_url: 'https://cloud.google.com/chronicle/docs',
  },
  {
    id: 'aws-security-hub',
    name: 'AWS Security Hub',
    category: 'Cloud Security',
    description: 'Integrate with AWS Security Hub for centralized security findings across AWS accounts.',
    functionality_type: 'Cloud Security Posture',
    fields: [
      {
        name: 'access_key_id',
        label: 'AWS Access Key ID',
        type: 'text',
        required: true,
      },
      {
        name: 'secret_access_key',
        label: 'AWS Secret Access Key',
        type: 'password',
        required: true,
      },
      {
        name: 'region',
        label: 'AWS Region',
        type: 'text',
        required: true,
        default: 'us-east-1',
        placeholder: 'e.g., us-east-1',
      },
    ],
    docs_url: 'https://docs.aws.amazon.com/securityhub/',
  },
  {
    id: 'okta',
    name: 'Okta',
    category: 'Identity & Access',
    description: 'Integrate with Okta for identity and access management, SSO, and MFA.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'domain',
        label: 'Okta Domain',
        type: 'text',
        required: true,
        placeholder: 'dev-123456.okta.com',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://developer.okta.com/docs/reference/',
  },
  {
    id: 'azure-ad',
    name: 'Azure Active Directory',
    category: 'Identity & Access',
    description: 'Connect to Azure AD (Entra ID) for identity management, authentication logs, and conditional access.',
    functionality_type: 'Identity & Access Management',
    fields: [
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_id',
        label: 'Client ID',
        type: 'text',
        required: true,
      },
      {
        name: 'client_secret',
        label: 'Client Secret',
        type: 'password',
        required: true,
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/azure/active-directory/',
  },
  {
    id: 'palo-alto',
    name: 'Palo Alto Networks',
    category: 'Network Security',
    description: 'Integrate with Palo Alto Networks firewalls and Panorama for policy management and threat prevention.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'hostname',
        label: 'Firewall/Panorama Hostname',
        type: 'text',
        required: true,
        placeholder: 'firewall.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
    ],
    docs_url: 'https://docs.paloaltonetworks.com/pan-os/10-0/pan-os-panorama-api',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: 'Network Security',
    description:
      'Cloudflare WAF, Zero Trust Gateway, and Access response actions, plus read-only IP/domain threat lookups. Lets Vigil propose and (with approval) execute WAF blocks, Gateway DNS/HTTP block policies, and Zero Trust session revocations.',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText:
          'Create at Cloudflare → My Profile → API Tokens. Required scopes: Zone:Firewall Services:Edit, Account:Zero Trust:Edit, Account:Access:Edit, Account:Account Analytics:Read.',
      },
      {
        name: 'account_id',
        label: 'Account ID',
        type: 'text',
        required: false,
        helpText: 'Required for Zero Trust Gateway and Access actions.',
      },
      {
        name: 'zone_id',
        label: 'Default Zone ID',
        type: 'text',
        required: false,
        helpText:
          'Optional default zone for WAF rules. Individual actions may override this.',
      },
    ],
    docs_url: 'https://developers.cloudflare.com/api/',
  },
  {
    id: 'decoy_controller',
    name: 'Decoy Controller',
    category: 'Network Security',
    description:
      'Decoy steering for the honey-routing posture: transparently redirects a suspicious source into the instrumented decoy farm on a short TTL lease — no deny signal reaches the source. Vigil decides, leases, and audits; the controller programs the network. Ships with the reference decoy-controller service (services/decoy_controller/).',
    functionality_type: 'Network Protection',
    fields: [
      {
        name: 'base_url',
        label: 'Controller URL',
        type: 'text',
        required: true,
        placeholder: 'http://decoy-controller:8484',
        helpText:
          'Base URL of the decoy-controller enforcement service (compose: http://decoy-controller:8484). Selecting the controller steering backend requires this integration.',
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText:
          'Bearer token the controller requires on every steering call (DECOY_CONTROLLER_TOKEN). Every request is denied without it.',
      },
    ],
  },
  {
    id: 'cloudforce_one',
    name: 'Cloudflare Cloudforce One',
    category: 'Threat Intelligence',
    description:
      'Cloudforce One STIX/TAXII 2.1 threat-intel feeds. Vigil polls configured collections, normalizes indicators, and enriches findings whose IOCs match. Operates independently of the Cloudflare WAF/Zero Trust integration so customers can subscribe to either or both.',
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText:
          'Cloudflare API token with Account:Cloudforce One:Read scope.',
      },
      {
        name: 'taxii_server_url',
        label: 'TAXII 2.1 Discovery URL',
        type: 'url',
        required: true,
        default: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/cloudforce-one/threat-events/taxii2/',
        placeholder: 'https://api.cloudflare.com/.../taxii2/',
        helpText:
          'TAXII 2.1 discovery endpoint. Substitute {account_id} with your Cloudflare account ID.',
      },
      {
        name: 'collection_ids',
        label: 'Collection IDs',
        type: 'text',
        required: true,
        placeholder: 'collection-uuid-1,collection-uuid-2',
        helpText:
          'Comma-separated list of TAXII collection IDs to poll. Leave empty to skip polling.',
      },
      {
        name: 'poll_interval_seconds',
        label: 'Poll Interval (seconds)',
        type: 'number',
        required: false,
        default: 900,
        helpText: 'How often Vigil pulls the latest indicators. Default 900 (15 min); minimum enforced server-side is 60.',
      },
    ],
    docs_url: 'https://developers.cloudflare.com/security-center/cloudforce-one/',
  },
  {
    id: 'jira',
    name: 'Jira',
    category: 'Incident Management',
    description: 'Create and manage security incidents in Jira.',
    functionality_type: 'Incident Tracking & SOAR',
    fields: [
      {
        name: 'url',
        label: 'Jira URL',
        type: 'url',
        required: true,
        placeholder: 'https://your-domain.atlassian.net',
      },
      {
        name: 'username',
        label: 'Email/Username',
        type: 'text',
        required: true,
      },
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        helpText: 'Create API token at https://id.atlassian.com/manage-profile/security/api-tokens',
      },
      {
        name: 'project_key',
        label: 'Default Project Key',
        type: 'text',
        required: false,
        placeholder: 'SEC',
        helpText: 'Optional: Default project for creating issues',
      },
    ],
    docs_url: 'https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/',
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communications',
    description: 'Send security alerts and notifications to Slack channels.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'bot_token',
        label: 'Bot Token',
        type: 'password',
        required: true,
        placeholder: 'xoxb-your-bot-token',
        helpText: 'Create a Slack app at https://api.slack.com/apps',
      },
      {
        name: 'default_channel',
        label: 'Default Channel',
        type: 'text',
        required: false,
        placeholder: '#security-alerts',
        helpText: 'Optional: Default channel for notifications',
      },
    ],
    docs_url: 'https://api.slack.com/tutorials',
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    category: 'Communications',
    description: 'Create incidents and send alerts through PagerDuty for on-call management.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'api_token',
        label: 'API Token',
        type: 'password',
        required: true,
        placeholder: 'Your PagerDuty API token',
        helpText: 'Create API key at https://support.pagerduty.com/docs/api-access-keys',
      },
      {
        name: 'integration_key',
        label: 'Integration Key',
        type: 'password',
        required: true,
        placeholder: 'Service integration key',
        helpText: 'Events API v2 integration key for your service',
      },
      {
        name: 'default_urgency',
        label: 'Default Urgency',
        type: 'select',
        required: false,
        default: 'high',
        options: [
          { value: 'high', label: 'High' },
          { value: 'low', label: 'Low' },
        ],
      },
    ],
    docs_url: 'https://developer.pagerduty.com/docs/ZG9jOjExMDI5NTgw-events-api-v2-overview',
  },
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    category: 'Communications',
    description: 'Send security alerts and notifications to Microsoft Teams channels.',
    functionality_type: 'Alerting & Collaboration',
    fields: [
      {
        name: 'webhook_url',
        label: 'Webhook URL',
        type: 'password',
        required: true,
        placeholder: 'https://your-org.webhook.office.com/webhookb2/...',
        helpText: 'Create incoming webhook in Teams channel settings',
      },
      {
        name: 'tenant_id',
        label: 'Tenant ID',
        type: 'text',
        required: false,
        placeholder: 'Azure AD tenant ID (optional)',
        helpText: 'Optional: For advanced Graph API integration',
      },
    ],
    docs_url: 'https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook',
  },
  {
    id: 'hybrid-analysis',
    name: 'Hybrid Analysis',
    category: 'Sandbox Analysis',
    description: 'Analyze suspicious files using Hybrid Analysis sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Get your API key from https://www.hybrid-analysis.com/my-account?tab=api-key',
      },
    ],
    docs_url: 'https://www.hybrid-analysis.com/docs/api/v2',
  },
  {
    id: 'joe-sandbox',
    name: 'Joe Sandbox',
    category: 'Sandbox Analysis',
    description: 'Analyze malware using Joe Sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
      },
      {
        name: 'api_url',
        label: 'API URL',
        type: 'url',
        required: true,
        default: 'https://jbxcloud.joesecurity.org/api',
        helpText: 'Use https://jbxcloud.joesecurity.org/api for Joe Sandbox Cloud',
      },
    ],
    docs_url: 'https://www.joesecurity.org/joe-sandbox-cloud',
  },
  {
    id: 'anyrun',
    name: 'ANY.RUN',
    category: 'Sandbox Analysis',
    description: 'Interactive malware analysis using ANY.RUN sandbox.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'Get your API key from https://any.run/api-documentation/',
      },
    ],
    docs_url: 'https://any.run/api-documentation/',
  },
  {
    id: 'cape-sandbox',
    name: 'CAPE Sandbox',
    category: 'Sandbox Analysis',
    description: 'Detonate files and URLs in a self-hosted CAPEv2 sandbox for behavioral analysis, IOCs, and PCAPs.',
    functionality_type: 'Malware Analysis',
    fields: [
      {
        name: 'url',
        label: 'CAPE URL',
        type: 'url',
        required: true,
        placeholder: 'https://cape.example.com',
      },
      {
        name: 'api_key',
        label: 'API Key',
        type: 'password',
        required: true,
        helpText: 'CAPEv2 REST API token, from your CAPE deployment.',
      },
    ],
    docs_url: 'https://capev2.readthedocs.io/en/latest/usage/api.html',
  },
  {
    id: 'atomic-red-team',
    name: 'Atomic Red Team',
    category: 'Forensics & Analysis',
    description: 'Invoke one Atomic Red Team technique against a named range or staging replica. Operator installs the runner; Vigil does not vendor the atomics repo.',
    functionality_type: 'Adversary Emulation',
    fields: [
      {
        name: 'runner_path',
        label: 'Runner path',
        type: 'text',
        required: true,
        placeholder: '/usr/local/bin/art-runner',
        helpText: 'Operator-installed executable. Invoked as `<runner> --technique <id>` with optional `--atomics-path`.',
      },
      {
        name: 'atomics_path',
        label: 'Atomics path',
        type: 'text',
        required: false,
        placeholder: '/opt/atomic-red-team/atomics',
        helpText: 'Directory of Atomic YAML tests. Leave empty if the runner has its own default.',
      },
    ],
    docs_url: 'https://github.com/redcanaryco/atomic-red-team',
  },

  {
    id: 'vstrike',
    name: 'CloudCurrent VStrike',
    category: 'Network Security',
    description:
      "Embed VStrike's network topology UI inside Vigil case investigations. Vigil drives which network and what kill-chain to play; VStrike streams the visualization back via WebSocket. Provides segment, criticality, mission-system, blast-radius, and attack-path enrichment to every Vigil agent.",
    functionality_type: 'Data Enrichment',
    fields: [
      {
        name: 'url',
        label: 'VStrike Base URL',
        type: 'url',
        required: true,
        placeholder: 'https://vstrike.net',
        helpText: 'Base URL of your VStrike deployment.',
      },
      {
        name: 'username',
        label: 'Username',
        type: 'text',
        required: true,
        placeholder: 'deeptempo_manager',
        helpText:
          'VStrike account username. Vigil exchanges username + password for a JWT via /mcp-login and refreshes it automatically — no API key paste needed.',
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        required: true,
        placeholder: 'Password for the VStrike account',
        helpText:
          'VStrike account password. Stored encrypted at ~/.vigil/secrets.enc — never written to disk in plaintext.',
      },
      {
        name: 'verify_ssl',
        label: 'Verify SSL Certificate',
        type: 'boolean',
        default: true,
      },
      {
        name: 'ca_cert_path',
        label: 'CA Certificate Path',
        type: 'text',
        required: false,
        placeholder: '/etc/vigil/certs/root-ca.pem',
        helpText: 'PEM trusted for this integration only, in place of the default store: the private CA that signed the server certificate. A path on the Vigil backend host; mount it into the container. Leave blank for the default store. Ignored when SSL verification is off.',
      },
    ],
    docs_url: 'https://cloudcurrent.biz/vstrike',
  },
]

export const INTEGRATION_CATEGORIES = [
  'Reference / Platform',
  'Threat Intelligence',
  'EDR/XDR',
  'SIEM',
  'Data Pipeline',
  'Cloud Security',
  'Identity & Access',
  'Network Security',
  'Incident Management',
  'Communications',
  'Sandbox Analysis',
  'Forensics & Analysis',
  'Custom',
]

let customIntegrations: IntegrationMetadata[] = []

let allIntegrations: IntegrationMetadata[] = [...INTEGRATIONS]

export async function loadCustomIntegrations(): Promise<void> {
  try {
    const response = await fetch(`${basePath}/api/custom-integrations/list`, {
      credentials: 'include',
    })
    const data = await response.json()
    
    if (data.success && data.integrations) {
      customIntegrations = data.integrations.map((metadata: any) => ({
        ...metadata,
        is_custom: true,
      }))
      
      allIntegrations = [...INTEGRATIONS, ...customIntegrations]
      
      console.log(`Loaded ${customIntegrations.length} custom integrations`)
    }
  } catch (error) {
    console.error('Error loading custom integrations:', error)
    customIntegrations = []
    allIntegrations = [...INTEGRATIONS]
  }
}

export function getAllIntegrations(): IntegrationMetadata[] {
  return allIntegrations
}

